# Generated by Django 3.2.5 on 2021-07-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weather_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
